<?php

namespace Database\Factories;

use App\Enums\Status;
use App\Models\Category;
use App\Models\Location;
use App\Models\Media;
use App\Models\Potential;
use App\Models\User;
use Database\Factories\Metadata\MetadataFactory;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Potential>
 */
class PotentialFactory extends Factory
{
    protected $model = Potential::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $faker = $this->faker;

        // Resolve or create a category to align dynamic metadata
        $category = Category::inRandomOrder()->first();
        if (!$category) {
            $category = Category::factory()->umkm()->create();
        }

        return [
            'category_id' => $category->id,
            'title' => $faker->words(3, true),
            // slug is auto-generated by PotentialObserver
            'description' => $faker->paragraphs(2, true),
            'status' => $faker->randomElement(Status::cases())->value,
            'cover_image_id' => Media::factory(),
            'location_id' => Location::factory(),
            'metadata' => MetadataFactory::generateFor($category->slug, $faker),
            'is_featured' => $faker->boolean(20), // 20% chance of being featured
            'created_by_id' => User::factory(),
        ];
    }
}
